version: '3.9'

networks:
  'laravel-network':
    driver: bridge

services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    networks:
      - 'laravel-network'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD}"]
      retries: 3
      timeout: 5s
  
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-web:8.0
    container_name: '${APP_NAME}-server'
    depends_on:
      - db
    ports:
      - '${APP_PORT:-80}:80'
    stdin_open: true
    tty: true
    volumes:
      - ./src:/var/www/html
      - ./data/logs/apache:/var/log/apache2
    networks:
      - 'laravel-network'